In [13]:
import numpy as np
import pandas as pd
import re

In [19]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_excel("flats.xlsx")

In [3]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.2+ KB

In [5]:
df = df.drop_duplicates()

In [8]:
df = df.drop(columns=['property_id', 'link'])

In [10]:
df.isna().sum()

property_name         0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
dtype: int64

In [11]:
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1824,3 BHK Flat in Sector 67 Gurgaon,Bestech Park View Spa Next4.0 ★,2.32 Crore,"₹ 11,989/sq.ft.",Super Built up area 1935(179.77 sq.m.)Carpet a...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Sector 67 Gurgaon, Gurgaon, Haryana",14th of 15 Floors,North-East,5 to 10 Year Old,"['Omaxe City Centre Mall', 'Golf Course Extens...",Bestech park view spa next is one of the most ...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '7 Li...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of..."
95,2 BHK Flat in Sector 68 Gurgaon,Supertech Hues,93 Lac,"₹ 8,611/sq.ft.",Carpet area: 1080 (100.34 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 68, Sector 68 Gurgaon, Gurgaon, Haryana",11st of 11 Floors,NaN,undefined,NaN,Best in class property available at sector 68 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety5 out of 5', ..."
3021,3 BHK Flat in Sector 103 Gurgaon,Spire Woods Now Ananda by Alpha corp,1.25 Crore,"₹ 6,902/sq.ft.",Carpet area: 1811 (168.25 sq.m.),3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room","Sector 103 Gurgaon, Gurgaon, Haryana",11st of 13 Floors,NaN,Under Construction,"['State bank ATM', 'Dr. Hitesh Dawar', 'Bhardw...",Spire woods now ananda by alpha corp in sector...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1041,4 BHK Flat in Sector 37D Gurgaon,BPTP Terra3.8 ★,1.6 Crore,"₹ 7,302/sq.ft.",Super Built up area 2191(203.55 sq.m.)Built Up...,4 Bedrooms,3 Bathrooms,3+ Balconies,Others,"A701, Sector 37D Gurgaon, Gurgaon, Haryana",7th of 23 Floors,North,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This is a super luxury property which is situa...,"['1 Wardrobe', '5 Fan', '1 Exhaust Fan', '21 L...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2536,3 BHK Flat in Sector 85 Gurgaon,Godrej Air,1.75 Crore,"₹ 9,589/sq.ft.",Built Up area: 1825 (169.55 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 85, Sector 85 Gurgaon, Gurgaon, Haryana",27th of 27 Floors,NaN,undefined,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",A5-2701 5 ac and modular kitchen with hob and ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [12]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                             73
Tulip Violet4.3 ★                            40
Shapoorji Pallonji Joyville Gurugram4.0 ★    39
Signature Global Park4.0 ★                   36
Shree Vardhman Victoria3.8 ★                 35
                                             ..
shree kirpalu gi sector 52                    1
Meditech Apartment                            1
Mariners Home                                 1
IMT View Society                              1
Spire Woods Now Ananda by Alpha corp          1
Name: count, Length: 639, dtype: int64

In [15]:
#https://www.thisdot.co/blog/understanding-regex
#Replace one or more(+) number (\d) followed by "." followed by numbers(\d+) followed by single space (?\s) followed by single star(?*) --> Replace with empty string ''
df['society'] = df['society'].apply(lambda x:re.sub(r'\d+(\.\d+)?\s?★','', str(x)))

df['society'] = df['society'].str.lower()

df['society'] = df['society'].apply(lambda x:str(x).strip())

In [16]:
df['society'].value_counts()

society
tulip violet                            75
ss the leaf                             74
shapoorji pallonji joyville gurugram    45
dlf new town heights                    38
signature global park                   36
                                        ..
imt view society                         1
professional society                     1
unitech harmony                          1
.                                        1
spire woods now ananda by alpha corp     1
Name: count, Length: 605, dtype: int64

In [17]:
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2877,2 BHK Flat in Sector 86 Gurgaon,pyramid elite,45 Lac,"₹ 7,846/sq.ft.",Carpet area: 573.54 (53.28 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"1208 & 1508, Sector 86 Gurgaon, Gurgaon, Haryana",12nd of 14 Floors,NaN,Under Construction,"['V3S Sapphire Ninety Mall', 'Sector 86 Road',...",Its surrounding dlf skycourt and gurgaon unive...,NaN,"['Intercom Facility', 'Lift(s)', 'Park', 'Shop...","['Safety4.5 out of 5', 'Lifestyle5 out of 5', ..."
2912,2 BHK Flat in Sohna,gls arawali homes,26.5 Lac,"₹ 4,600/sq.ft.",Super Built up area 576(53.51 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sohna, Gurgaon, Haryana",5th of 13 Floors,NaN,0 to 1 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",Tower 13 floor 5th house no. 508. Freehold pro...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Management4 out of 5', 'Green Area5 out of 5..."
751,2 BHK Flat in Sector 60 Gurgaon,ireo skyon,2.12 Crore,"₹ 15,531/sq.ft.",Super Built up area 1365(126.81 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,2 Balconies,Pooja Room,"201, Sector 60 Gurgaon, Gurgaon, Haryana",2nd of 12 Floors,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Looking for a 2 bhk property for sale in gurga...,"['3 Wardrobe', '1 Water Purifier', '11 Fan', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
974,3 BHK Flat in Sector 106 Gurgaon,paras dews,1.13 Crore,"₹ 6,406/sq.ft.",Super Built up area 1760(163.51 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room","Sector 106 Gurgaon, Gurgaon, Haryana",18th of 24 Floors,North-West,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Paras dews is one of the most popular destinat...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
710,4 BHK Flat in Sector 110 Gurgaon,indiabulls enigma,3.3 Crore,"₹ 9,850/sq.ft.",Super Built up area 3350(311.23 sq.m.),4 Bedrooms,5 Bathrooms,3 Balconies,Servant Room,"N/a, Sector 110 Gurgaon, Gurgaon, Haryana",7th of 15 Floors,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Located in the popular residential address of ...,[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [20]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
3.4 Crore           14
2.15 Crore          14
2.45 Crore          14
1.32 Crore          13
82 Lac              13
78 Lac              13
38 Lac              13
3.25 Crore          13
2.7 Crore           13
92 Lac              13
42 Lac              12
5 Crore             12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
32 Lac              11
Price on Request    11
88 Lac              11
1.08 Crore          11
25 Lac              11
26 Lac              10
1.78 Crore          10
87 Lac              10
1.12 Crore          10
28 Lac              10
1.28 Crore          10
2.55 Crore          10
2.05 Crore           9
36 Lac               9
2.85 Crore           9
3.45 Crore           9
1.72 Crore           9
99 Lac               9
22 Lac               9
4 Crore              9
1.68 Crore           9
27 Lac               8
1.54 Crore           8
3.2 Crore            8
98 Lac               8
1.76 Crore           8
6 Crore              8
86 Lac               8
56 Lac               8
6.5 Crore            8
48 Lac               8
4.25 Crore           8
2.75 Crore           8
1.18 Crore           8
20 Lac               8
1.26 Crore           8
97 Lac               7
3.3 Crore            7
3.7 Crore            7
72 Lac               7
1.27 Crore           7
1.19 Crore           7
1.36 Crore           7
2.9 Crore            7
1.02 Crore           7
46 Lac               7
39 Lac               7
1.99 Crore           7
1.29 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.01 Crore           6
1.49 Crore           6
1.98 Crore           6
3.9 Crore            6
3.65 Crore           6
37 Lac               6
5.5 Crore            6
1.07 Crore           6
21 Lac               6
2.95 Crore           6
96 Lac               6
1.16 Crore           6
1.13 Crore           6
1.34 Crore           6
54 Lac               6
3.35 Crore           6
1.51 Crore           6
1.14 Crore           6
3.05 Crore           6
4.1 Crore            6
1.39 Crore           6
71.5 Lac             6
1.17 Crore           5
1.92 Crore           5
3.75 Crore           5
2.22 Crore           5
6.75 Crore           5
1.44 Crore           5
1.24 Crore           5
1.69 Crore           5
1.82 Crore           5
49 Lac               5
1.33 Crore           5
2.78 Crore           5
1.91 Crore           5
1.43 Crore           5
66 Lac               5
1.83 Crore           5
1.47 Crore           5
29 Lac               5
4.5 Crore            5
2.12 Crore           5
2.29 Crore           5
93 Lac               5
1.62 Crore           5
68 Lac               5
64 Lac               5
1.79 Crore           5
1.93 Crore           5
24 Lac               5
41.5 Lac             4
5.6 Crore            4
1.52 Crore           4
1.23 Crore           4
1.22 Crore           4
4.3 Crore            4
28.5 Lac             4
2.09 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
67 Lac               4
58 Lac               4
1.37 Crore           4
74 Lac               4
1.31 Crore           4
1.58 Crore           4
6.15 Crore           4
3.95 Crore           4
3.6 Crore            4
1.77 Crore           4
5.9 Crore            4
7 Crore              4
73 Lac               4
89 Lac               4
1.48 Crore           4
1.71 Crore           4
33 Lac               4
31 Lac               4
4.85 Crore           4
1.64 Crore           4
1.66 Crore           4
36.5 Lac             4
3.1 Crore            4
52 Lac               3
2.01 Crore           3
51 Lac               3
2.08 Crore           3
1.41 Crore           3
83 Lac               3
94 Lac               3
2.24 Crore           3
3.49 Crore           3
2.51 Crore           3
1.67 Crore           3
47 Lac               3
1.21 Crore           3
4.8 Crore            3
4.75 Crore           3
2.36 Crore           3
72.5 Lac             3
1.04 Crore           3
64.5 Lac             3
2.79 Crore           3
2.33 Crore           3
1.88 Crore           3
5.8 Crore            3
3.85 Crore           3
91 Lac               3
1.09 Crore           3
1.63 Crore           3
2.03 Crore           3
4.2 Crore            3
3.15 Crore           3
34 Lac               3
1.57 Crore           3
3.8 Crore            3
69 Lac               3
2.28 Crore           3
84 Lac               3
8 Crore              2
2.23 Crore           2
53 Lac               2
2.17 Crore           2
27.1 Lac             2
77.5 Lac             2
8.5 Crore            2
2.14 Crore           2
6.2 Crore            2
2.52 Crore           2
53.5 Lac             2
2.58 Crore           2
4.49 Crore           2
1.46 Crore           2
4.26 Crore           2
2.57 Crore           2
2.99 Crore           2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
2.41 Crore           2
5.2 Crore            2
2.02 Crore           2
14 Crore             2
2.87 Crore           2
2.26 Crore           2
56.2 Lac             2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.13 Crore           2
4.55 Crore           2
2.04 Crore           2
25.5 Lac             2
27.75 Lac            2
4.45 Crore           2
11 Crore             2
4.7 Crore            2
7.5 Crore            2
88.5 Lac             2
37.1 Lac             1
54.8 Lac             1
63.4 Lac             1
2.38 Crore           1
2.64 Crore           1
3.98 Crore           1
4.02 Crore           1
7.4 Crore            1
97.5 Lac             1
39.5 Lac             1
2.06 Crore           1
2.07 Crore           1
64.45 Lac            1
44 Lac               1
2.49 Crore           1
3.78 Crore           1
2.92 Crore           1
9 Crore              1
61 Lac               1
4.21 Crore           1
89.77 Lac            1
4.16 Crore           1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
68.85 Lac            1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
1.97 Crore           1
82.5 Lac             1
13.2 Crore           1
98.88 Lac            1
3.99 Crore           1
37.5 Lac             1
2.32 Crore           1
2.44 Crore           1
57 Lac               1
1.74 Crore           1
95.5 Lac             1
94.5 Lac             1
2.96 Crore           1
29.8 Lac             1
6.02 Crore           1
96.07 Lac            1
7.9 Crore            1
32.5 Lac             1
3.23 Crore           1
19 Lac               1
70.85 Lac            1
97.04 Lac            1
40.3 Lac             1
3.72 Crore           1
88.4 Lac             1
94.99 Lac            1
1.53 Crore           1
7.52 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
2.69 Crore           1
86.99 Lac            1
9.95 Crore           1
86.92 Lac            1
9.2 Crore            1
49.5 Lac             1
2.54 Crore           1
16 Lac               1
7.8 Crore            1
2.86 Crore           1
15 Crore             1
4.4 Crore            1
9.3 Crore            1
5.3 Crore            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
2.72 Crore           1
98.1 Lac             1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
11.25 Crore          1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
price                1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
55.6 Lac             1
2.63 Crore           1
5.15 Crore           1
47.5 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
2.77 Crore           1
55.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
9.14 Crore           1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
62.5 Lac             1
Name: count, dtype: int64

In [42]:
def lac_to_crore(amount):
    try:
        if type(amount) == float:
            return amount
        if str(amount[1]).lower()=='crore':
            return round(float(amount[0]), 2)
        return round(float(amount[0])/100, 2)
    except:
        print("Error value : ",amount)

In [45]:
df[df['price'] == 'Price on Request']

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
286,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating

In [46]:
df = df[df['price'] != 'Price on Request']
df = df[df['price'] != 'price']

In [47]:
df['price'] = df['price'].str.split(' ').apply(lac_to_crore)

In [48]:
df.head(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [49]:
df['area'].value_counts()

area
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 9,000/sq.ft.       8
₹ 7,000/sq.ft.       8
₹ 11,111/sq.ft.      7
₹ 9,230/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 8,205/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,142/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 7,692/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 7,407/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 8,108/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 13,913/sq.ft.      4
₹ 5,660/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 7,250/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 11,666/sq.ft.      4
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 8,784/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 16,470/sq.ft.      3
₹ 6,470/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 7,750/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 13,000/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 8,400/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 8,389/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 6,086/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 13,870/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 10,555/sq.ft.      3
₹ 10,204/sq.ft.      3
₹ 9,500/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 5,325/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 7,150/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 9,128/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 11,765/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 8,733/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 9,797/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 6,679/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 5,820/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 5,588/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 15,551/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 18,518/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 6,422/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 6,373/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 9,105/sq.ft.       2
₹ 7,878/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 12,212/sq.ft.      2
₹ 15,263/sq.ft.      2
₹ 20,687/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 6,333/sq.ft.       2
₹ 4,857/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 8,290/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 8,632/sq.ft.       2
₹ 5,808/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 10,237/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 7,185/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 15,294/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 58/sq.ft.          2
₹ 6,927/sq.ft.       2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 12,012/sq.ft.      2
₹ 3,695/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 7,863/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,000/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 8,524/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 8,720/sq.ft.       2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 6,985/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 5,111/sq.ft.       2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 8,310/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 6,686/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 9,791/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 15,195/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 7,490/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,097/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 14,303/sq.ft.      2
₹ 6,402/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 7,585/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 5,882/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 18,000/sq.ft.      2
₹ 9,166/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 12,782/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 4,271/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 5,291/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 16,960/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 9,851/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 6,200/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 5,714/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 7,234/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 4,200/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 6,859/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 12,250/sq.ft.      2
₹ 6,722/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 7,857/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 5,405/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 6,178/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 5,128/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 13,281/sq.ft.      2
₹ 21,538/sq.ft.      2
₹ 13,383/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 6,616/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 7,884/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 5,528/sq.ft.       2
₹ 9,854/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,811/sq.ft.       2
₹ 8,279/sq.ft.       2
₹ 7,945/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 5,649/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 200,000/sq.ft.     2
₹ 8,347/sq.ft.       1
₹ 14,795/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 8,042/sq.ft.       1
₹ 8,052/sq.ft.       1
₹ 8,120/sq.ft.       1
₹ 4,637/sq.ft.       1
₹ 7,951/sq.ft.       1
₹ 6,426/sq.ft.       1
₹ 17,691/sq.ft.      1
₹ 13,989/sq.ft.      1
₹ 6,914/sq.ft.       1
₹ 6,550/sq.ft.       1
₹ 6,601/sq.ft.       1
₹ 9,218/sq.ft.       1
₹ 10,375/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 10,205/sq.ft.      1
₹ 11,654/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 12,044/sq.ft.      1
₹ 8,123/sq.ft.       1
₹ 11,251/sq.ft.      1
₹ 19,943/sq.ft.      1
₹ 5,491/sq.ft.       1
₹ 5,759/sq.ft.       1
₹ 17,729/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 6,032/sq.ft.       1
₹ 6,951/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 15,901/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 10,656/sq.ft.      1
₹ 7,360/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 13,480/sq.ft.      1
₹ 11,989/sq.ft.      1
₹ 7,714/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 8,297/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 4,923/sq.ft.       1
₹ 6,159/sq.ft.       1
₹ 9,734/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 15,130/sq.ft.      1
₹ 7,654/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 3,516/sq.ft.       1
₹ 14,267/sq.ft.      1
₹ 12,437/sq.ft.      1
₹ 2,666/sq.ft.       1
₹ 8,737/sq.ft.       1
₹ 13,575/sq.ft.      1
₹ 4,603/sq.ft.       1
₹ 11,580/sq.ft.      1
₹ 7,079/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 5,576/sq.ft.       1
₹ 5,910/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 8,554/sq.ft.       1
₹ 2,051/sq.ft.       1
₹ 10,743/sq.ft.      1
₹ 7,891/sq.ft.       1
₹ 14,358/sq.ft.      1
₹ 6,007/sq.ft.       1
₹ 18,688/sq.ft.      1
₹ 7,950/sq.ft.       1
₹ 4,602/sq.ft.       1
₹ 4,345/sq.ft.       1
₹ 9,002/sq.ft.       1
₹ 20,666/sq.ft.      1
₹ 5,813/sq.ft.       1
₹ 11,142/sq.ft.      1
₹ 6,554/sq.ft.       1
₹ 7,931/sq.ft.       1
₹ 17,543/sq.ft.      1
₹ 4,886/sq.ft.       1
₹ 7,614/sq.ft.       1
₹ 6,168/sq.ft.       1
₹ 6,033/sq.ft.       1
₹ 3,713/sq.ft.       1
₹ 6,194/sq.ft.       1
₹ 9/sq.ft.           1
₹ 4,108/sq.ft.       1
₹ 7,679/sq.ft.       1
₹ 10,309/sq.ft.      1
₹ 5,265/sq.ft.       1
₹ 8,367/sq.ft.       1
₹ 4,933/sq.ft.       1
₹ 7,068/sq.ft.       1
₹ 9,130/sq.ft.       1
₹ 591/sq.ft.         1
₹ 4,941/sq.ft.       1
₹ 7,893/sq.ft.       1
₹ 3,671/sq.ft.       1
₹ 10,627/sq.ft.      1
₹ 6,089/sq.ft.       1
₹ 4,942/sq.ft.       1
₹ 10,754/sq.ft.      1
₹ 5,904/sq.ft.       1
₹ 13,522/sq.ft.      1
₹ 11,794/sq.ft.      1
₹ 15,124/sq.ft.      1
₹ 4,673/sq.ft.       1
₹ 6,485/sq.ft.       1
₹ 14,632/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 6,694/sq.ft.       1
₹ 15,262/sq.ft.      1
₹ 9,696/sq.ft.       1
₹ 5,739/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 7,262/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 5,965/sq.ft.       1
₹ 3,352/sq.ft.       1
₹ 4,600/sq.ft.       1
₹ 7,010/sq.ft.       1
₹ 6,842/sq.ft.       1
₹ 6,137/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 7,920/sq.ft.       1
₹ 11,600/sq.ft.      1
₹ 14,838/sq.ft.      1
₹ 7,760/sq.ft.       1
₹ 13,177/sq.ft.      1
₹ 9,016/sq.ft.       1
₹ 6,870/sq.ft.       1
₹ 11,920/sq.ft.      1
₹ 6,552/sq.ft.       1
₹ 16,445/sq.ft.      1
₹ 13,984/sq.ft.      1
₹ 15,982/sq.ft.      1
₹ 8,266/sq.ft.       1
₹ 4,106/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 9,519/sq.ft.       1
₹ 8,734/sq.ft.       1
₹ 21,922/sq.ft.      1
₹ 10,380/sq.ft.      1
₹ 8,700/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 5,413/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 5,507/sq.ft.       1
₹ 7,453/sq.ft.       1
₹ 17,488/sq.ft.      1
₹ 8,802/sq.ft.       1
₹ 6,435/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 8,404/sq.ft.       1
₹ 22,700/sq.ft.      1
₹ 6,998/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 8,446/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 8,095/sq.ft.       1
₹ 9,912/sq.ft.       1
₹ 11,209/sq.ft.      1
₹ 3,650/sq.ft.       1
₹ 3,664/sq.ft.       1
₹ 12,009/sq.ft.      1
₹ 15,560/sq.ft.      1
₹ 12,272/sq.ft.      1
₹ 4,456/sq.ft.       1
₹ 22,222/sq.ft.      1
₹ 22,346/sq.ft.      1
₹ 5,296/sq.ft.       1
₹ 10,306/sq.ft.      1
₹ 8,558/sq.ft.       1
₹ 8,124/sq.ft.       1
₹ 13,953/sq.ft.      1
₹ 14,658/sq.ft.      1
₹ 9,531/sq.ft.       1
₹ 6,648/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 11,559/sq.ft.      1
₹ 7,547/sq.ft.       1
₹ 9,091/sq.ft.       1
₹ 7,171/sq.ft.       1
₹ 13,513/sq.ft.      1
₹ 5,571/sq.ft.       1
₹ 8,823/sq.ft.       1
₹ 10,418/sq.ft.      1
₹ 11,725/sq.ft.      1
₹ 4,404/sq.ft.       1
₹ 6,556/sq.ft.       1
₹ 6,587/sq.ft.       1
₹ 10,697/sq.ft.      1
₹ 8,387/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 7,882/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 5,958/sq.ft.       1
₹ 11,497/sq.ft.      1
₹ 4,861/sq.ft.       1
₹ 9,380/sq.ft.       1
₹ 9,370/sq.ft.       1
₹ 9,264/sq.ft.       1
₹ 6,902/sq.ft.       1
₹ 5,541/sq.ft.       1
₹ 8,674/sq.ft.       1
₹ 13,425/sq.ft.      1
₹ 10,408/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 10,888/sq.ft.      1
₹ 10,483/sq.ft.      1
₹ 7,779/sq.ft.       1
₹ 10,452/sq.ft.      1
₹ 9,984/sq.ft.       1
₹ 5,214/sq.ft.       1
₹ 11,869/sq.ft.      1
₹ 10,924/sq.ft.      1
₹ 6,900/sq.ft.       1
₹ 15,102/sq.ft.      1
₹ 6,319/sq.ft.       1
₹ 4,545/sq.ft.       1
₹ 3,500/sq.ft.       1
₹ 9,076/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 6,751/sq.ft.       1
₹ 7,006/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 7,227/sq.ft.       1
₹ 7,066/sq.ft.       1
₹ 23,344/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 6,256/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 6,176/sq.ft.       1
₹ 8,602/sq.ft.       1
₹ 7,561/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 11,178/sq.ft.      1
₹ 4,807/sq.ft.       1
₹ 13,936/sq.ft.      1
₹ 11,854/sq.ft.      1
₹ 7,988/sq.ft.       1
₹ 10,094/sq.ft.      1
₹ 10,903/sq.ft.      1
₹ 11,525/sq.ft.      1
₹ 11,741/sq.ft.      1
₹ 6,165/sq.ft.       1
₹ 4,037/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 8,111/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 6,358/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 9,227/sq.ft.       1
₹ 15,360/sq.ft.      1
₹ 7,307/sq.ft.       1
₹ 6,389/sq.ft.       1
₹ 11,423/sq.ft.      1
₹ 11,386/sq.ft.      1
₹ 6,979/sq.ft.       1
₹ 11,923/sq.ft.      1
₹ 8,666/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 5,931/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 8,040/sq.ft.       1
₹ 5,789/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 8,907/sq.ft.       1
₹ 5,329/sq.ft.       1
₹ 4,700/sq.ft.       1
₹ 13,296/sq.ft.      1
₹ 8,840/sq.ft.       1
₹ 8,856/sq.ft.       1
₹ 3,864/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 5,443/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 4,869/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 6,083/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 5,367/sq.ft.       1
₹ 4,868/sq.ft.       1
₹ 4,458/sq.ft.       1
₹ 10,163/sq.ft.      1
₹ 4,931/sq.ft.       1
₹ 9,569/sq.ft.       1
₹ 9,459/sq.ft.       1
₹ 5,432/sq.ft.       1
₹ 9,102/sq.ft.       1
₹ 9,701/sq.ft.       1
₹ 8,264/sq.ft.       1
₹ 8,812/sq.ft.       1
₹ 6,502/sq.ft.       1
₹ 4,786/sq.ft.       1
₹ 10,815/sq.ft.      1
₹ 8,522/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 6,022/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 6,618/sq.ft.       1
₹ 8,850/sq.ft.       1
₹ 10,004/sq.ft.      1
₹ 8,240/sq.ft.       1
₹ 9,846/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 7,886/sq.ft.       1
₹ 6,023/sq.ft.       1
₹ 9,513/sq.ft.       1
₹ 11,190/sq.ft.      1
₹ 6,926/sq.ft.       1
₹ 9,310/sq.ft.       1
₹ 5,590/sq.ft.       1
₹ 4,587/sq.ft.       1
₹ 6,201/sq.ft.       1

In [54]:
df['area'] = (df['area'].str.split('/')).str.get(0).str.replace(',','').str.replace('₹ ', '')

In [55]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1221,4 BHK Flat in Gwal Pahari,krrish provence estate,5.50,9482,Super Built up area 5800(538.84 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","Gwal Pahari, Gurgaon, Haryana",11st of 26 Floors,East,0 to 1 Year Old,"['Tniy Toons School', 'Pathways School Gurgoan...",These units are a perfect combination of comfo...,NaN,"['Water purifier', 'Security / Fire Alarm', 'P...",NaN
583,3 BHK Flat in Sector 66 Gurgaon,emaar mgf the palm drive,3.50,16470,Super Built up area 2200(204.39 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"111, Sector 66 Gurgaon, Gurgaon, Haryana",6th of 17 Floors,North,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Park and pool facing apartment,"['5 AC', '1 Modular Kitchen', '1 Chimney', 'No...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4.5 out ..."
381,3 BHK Flat in Sector 85 Gurgaon,orris aster court premier,1.38,6509,Super Built up area 2120(196.95 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"Sector 85 Gurgaon, Gurgaon, Haryana",6th of 12 Floors,North-East,1 to 5 Year Old,"['Propose Metro Station', 'SS Omnia Mall', 'Na...",Ne facing apartment with open view. All rooms ...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1261,2 BHK Flat in Sector 84 Gurgaon,pivotal devaan,0.34,7039,Carpet area: 483 (44.87 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,Store Room,"108, Sector 84 Gurgaon, Gurgaon, Haryana",1st of 14 Floors,East,1 to 5 Year Old,"['Dwarka Expressway', 'RPS International Schoo...",Pivotal devaan pivotal infrastructure propelli...,"['1 Wardrobe', '3 Fan', '1 Exhaust Fan', '5 Li...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
842,3 BHK Flat in Sector 81 Gurgaon,dlf the ultima,2.40,11412,Super Built up area 2103(195.38 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"192, Sector 81 Gurgaon, Gurgaon, Haryana",19th of 30 Floors,North-West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Located in the popular residential address of ...,"['1 Fridge', '1 Fan', '1 Exhaust Fan', '1 Dini...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."

In [56]:
df['price_per_sqft'] = df['price_per_sqft'].astype(float)

In [57]:
df.isna().sum()

property_name         0
society               0
price                20
price_per_sqft        2
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1324
address              25
floorNum             21
facing              893
agePossession        20
nearbyLocations     110
description          19
furnishDetails      816
features            426
rating              348
dtype: int64

In [61]:
df = df[~df['bedRoom'].isna()]

In [62]:
df.isna().sum()

property_name         0
society               0
price                 1
price_per_sqft        1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1305
address               6
floorNum              2
facing              874
agePossession         1
nearbyLocations      91
description           0
furnishDetails      797
features            407
rating              329
dtype: int64

In [63]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [66]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

/tmp/ipykernel_92481/579309429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [67]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
265,2 BHK Flat in Sector 79 Gurgaon,godrej aria,1.10,7772.0,Super Built up area 1351(125.51 sq.m.),2,2 Bathrooms,3+ Balconies,NaN,"Sector 79 Gurgaon, Gurgaon, Haryana",4th of 15 Floors,North-East,0 to 1 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",Corner flat with north and east side open. Fac...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Amenities5 out of 5'..."
1633,3 BHK Flat in MG Road,suncity platinum towers,6.00,22346.0,Carpet area: 2685 (249.44 sq.m.),3,3 Bathrooms,2 Balconies,Servant Room,"MG Road, Gurgaon, Haryana",8th of 14 Floors,South-East,5 to 10 Year Old,"['Iffco Chowk', 'MG Road', 'Plaza Mall', 'MGF ...",3 bedroom 2685 sq.Ft. Middle floor apartment a...,"['3 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1697,2 BHK Flat in Sector 82 Gurgaon,vatika the seven lamps,0.89,8850.0,Super Built up area 1428.08(132.67 sq.m.)Carpe...,2,2 Bathrooms,2 Balconies,Study Room,"Sector 82 Gurgaon, Gurgaon, Haryana",14th of 16 Floors,East,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2bhk+study, 1430 sq. Ft., east...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
1731,3 BHK Flat in Sector 69 Gurgaon,tulip violet,1.60,10139.0,Super Built up area 1578(146.6 sq.m.),3,3 Bathrooms,2 Balconies,Pooja Room,"004, Sector 69 Gurgaon, Gurgaon, Haryana",Ground of 14 Floors,North-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Sun facing 3 bhk ground floor this beautiful 3...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1323,3 BHK Flat in Sector 59 Gurgaon,mahindra luminare,5.80,19173.0,Carpet area: 3025 (281.03 sq.m.),3,4 Bathrooms,3 Balconies,Servant Room,"3bhk Flat, Sector 59 Gurgaon, Gurgaon, Haryana",16th of 30 Floors,North-East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Metro World Ma...",3bhk flat for sale in mahindra luminare,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."

In [68]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [69]:
df['bathroom'] = df['bathroom'].str.split(" ").str.get(0).astype(int)

/tmp/ipykernel_92481/634729186.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bathroom'] = df['bathroom'].str.split(" ").str.get(0).astype(int)

In [70]:
df['bathroom'].value_counts()

bathroom
2    1044
3     989
4     636
5     169
1     112
6      42
7       5
Name: count, dtype: int64

In [71]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2247,2 BHK Flat in Sector 61 Gurgaon,pioneer park,1.60,11594.0,Carpet area: 1380 (128.21 sq.m.),2,2,2 Balconies,Servant Room,"Sector 61 Gurgaon, Gurgaon, Haryana",21st of 23 Floors,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Hong Kong Bazaar...",Check out this 2 bhk flat for sale in pioneer ...,"['2 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."
1832,3 BHK Flat in Sector 49 Gurgaon,vatika city,1.85,10578.0,Super Built up area 1748.87(162.48 sq.m.)Built...,3,3,1 Balcony,"Pooja Room,Store Room","Emilia, Sector 49 Gurgaon, Gurgaon, Haryana",7th of 17 Floors,South-West,5 to 10 Year Old,"['BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES b...",Excellent connectivity with dwarka expressway\...,NaN,"['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
1316,3 BHK Flat in Sector 103 Gurgaon,indiabulls centrum park,1.34,7486.0,Super Built up area 1790(166.3 sq.m.)Carpet ar...,3,3,3+ Balconies,Study Room,"Tower K, Sector 103 Gurgaon, Gurgaon, Haryana",13rd of 18 Floors,South-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...","Indiabulls centrum park in sector 103, gurgaon...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."
313,2 BHK Flat in Sector 103 Gurgaon,landmark the residency,0.90,6666.0,Super Built up area 1350(125.42 sq.m.),2,2,2 Balconies,NaN,"Sector 103 Gurgaon, Gurgaon, Haryana",1st of 14 Floors,South-West,1 to 5 Year Old,"['State bank ATM', 'Dr. Hitesh Dawar', 'Bhardw...",We are the proud owners of this 2 bhk apartmen...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Intercom Facility',...","['Connectivity4 out of 5', 'Lifestyle4 out of ..."
90,2 BHK Flat in Sector 37D Gurgaon,signature global city,1.10,9838.0,Carpet area: 1118 (103.87 sq.m.),2,2,2 Balconies,NaN,"Sector 93, Sector 37D Gurgaon, Gurgaon, Haryana",4th of 4 Floors,South,undefined,"['Sapphire 83 Mall Sector 83', 'Dwarka Express...",Best in class property available at sector 93 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."

In [72]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [73]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No', '0')

/tmp/ipykernel_92481/1973056465.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No', '0')

In [74]:
df['balcony'].value_counts()

balcony
3     974
3+    862
2     749
1     315
0      97
Name: count, dtype: int64

In [75]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2761,4 BHK Flat in Sector 9A Gurgaon,railway officers rpf society,1.30,5039.0,Built Up area: 2580 (239.69 sq.m.),4,4,3+,NaN,"Flat B-902, Sector 9A Gurgaon, Gurgaon, Haryana",9th of 11 Floors,East,undefined,NaN,4bhk multistorey apartment for resale in railw...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2863,3 BHK Flat in South City 1,unitech the palms,2.75,16768.0,Super Built up area 1640(152.36 sq.m.),3,3,2,NaN,"1401 Tower 4, South City 1, Gurgaon, Haryana",14th of 17 Floors,NaN,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Its fully furnished with imported modular kitc...,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Safety5 out of 5', 'Lifestyle5 out of 5', 'E..."
1061,4 BHK Flat in Sector 85 Gurgaon,ss the leaf,2.30,8179.0,Super Built up area 2812(261.24 sq.m.),4,4,3+,Servant Room,"B521, Sector 85 Gurgaon, Gurgaon, Haryana",8th of 26 Floors,South,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Located in the popular residential address of ...,"['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1828,3 BHK Flat in Sector 106 Gurgaon,paras dews,1.20,11605.0,Super Built up area 1665(154.68 sq.m.)Built Up...,3,3,3,Study Room,"C33, Sector 106 Gurgaon, Gurgaon, Haryana",12nd of 24 Floors,North-West,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Paras dews is one of gurgaon's most sought aft...,NaN,"['Water purifier', 'Centrally Air Conditioned'...",NaN
2874,3 BHK Flat in Sohna,signature global park,0.79,7308.0,Super Built up area 1081(100.43 sq.m.),3,2,3+,NaN,"A52, Sohna, Gurgaon, Haryana",4th of 4 Floors,NaN,Under Construction,"['Sector 55-56 metro', 'Global city centre', '...","A52, 4th floor with roof rights - Park 5 main ...",NaN,"['Security / Fire Alarm', 'Private Garden / Te...","['Management4 out of 5', 'Green Area5 out of 5..."

In [76]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [77]:
df['additionalRoom'].value_counts().shape

(49,)

In [79]:
df['additionalRoom'].isna().sum()

1305

In [80]:
df['additionalRoom'].fillna('Not Available', inplace=True)

/tmp/ipykernel_92481/2698836734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom'].fillna('Not Available', inplace=True)

In [84]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

/tmp/ipykernel_92481/4218856625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom'] = df['additionalRoom'].str.lower()

In [82]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,Not Available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,Not Available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,Not Available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [83]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
3rd   of 14 Floors          24
5th   of 14 Floors          24
8th   of 19 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 14 Floors          23
9th   of 9 Floors           23
5th   of 12 Floors          22
2nd   of 3 Floors           22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
10th   of 18 Floors         17
9th   of 13 Floors          17
7th   of 15 Floors          17
12nd   of 12 Floors         17
Ground of 1 Floors          17
7th   of 18 Floors          17
3rd   of 18 Floors          16
5th   of 15 Floors          16
9th   of 15 Floors          15
1st   of 3 Floors           15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
Ground of 4 Floors          13
3rd   of 13 Floors          13
5th   of 5 Floors           13
1st   of 2 Floors           13
7th   of 7 Floors           13
10th   of 26 Floors         13
6th   of 10 Floors          13
6th   of 15 Floors          12
10th   of 10 Floors         12
17th   of 17 Floors         11
4th   of 10 Floors          11
11st   of 18 Floors         11
9th   of 26 Floors          11
15th   of 19 Floors         11
9th   of 24 Floors          11
6th   of 6 Floors           11
16th   of 19 Floors         11
8th   of 8 Floors           11
8th   of 12 Floors          11
4th   of 13 Floors          11
7th   of 26 Floors          10
4th   of 12 Floors          10
7th   of 13 Floors          10
2nd   of 19 Floors          10
7th   of 21 Floors          10
12nd   of 18 Floors         10
6th   of 13 Floors          10
4th   of 15 Floors          10
1st   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
3rd   of 5 Floors           10
14th   of 15 Floors          9
14th   of 19 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
3rd   of 12 Floors           9
18th   of 19 Floors          9
8th   of 15 Floors           9
6th   of 16 Floors           9
15th   of 29 Floors          9
8th   of 22 Floors           9
9th   of 20 Floors           9
7th   of 17 Floors           9
13rd   of 14 Floors          9
7th   of 12 Floors           9
6th   of 26 Floors           9
12nd   of 19 Floors          8
10th   of 17 Floors          8
5th   of 9 Floors            8
3rd   of 15 Floors           8
2nd   of 8 Floors            8
9th   of 18 Floors           8
8th   of 24 Floors           8
10th   of 13 Floors          8
8th   of 26 Floors           8
1st   of 19 Floors           8
2nd   of 15 Floors           8
4th   of 26 Floors           8
12nd   of 26 Floors          8
3rd   of 19 Floors           8
8th   of 13 Floors           8
12nd   of 24 Floors          8
9th   of 12 Floors           8
5th   of 13 Floors           8
2nd   of 5 Floors            8
14th   of 24 Floors          8
4th   of 19 Floors           7
9th   of 19 Floors           7
16th   of 16 Floors          7
5th   of 29 Floors           7
11st   of 24 Floors          7
11st   of 11 Floors          7
2nd   of 13 Floors           7
7th   of 19 Floors           7
2nd   of 17 Floors           7
12nd   of 13 Floors          7
11st   of 26 Floors          7
1st   of 13 Floors           7
11st   of 13 Floors          7
8th   of 21 Floors           7
10th   of 21 Floors          7
8th   of 10 Floors           7
13rd   of 13 Floors          7
2nd   of 10 Floors           7
5th   of 20 Floors           7
12nd   of 15 Floors          7
11st   of 12 Floors          6
Ground of 16 Floors          6
5th   of 22 Floors           6
1st   of 5 Floors            6
1st   of 10 Floors           6
2nd   of 20 Floors           6
14th   of 27 Floors          6
16th   of 18 Floors          6
12nd   of 22 Floors          6
11st   of 19 Floors          6
17th   of 19 Floors          6
10th   of 29 Floors          6
10th   of 20 Floors          6
6th   of 9 Floors            6
19th   of 19 Floors          6
Ground of 3 Floors           6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
4th   of 18 Floors           6
15th   of 15 Floors          6
5th   of 25 Floors           6
5th   of 10 Floors           6
10th   of 15 Floors          6
7th   of 20 Floors           6
8th   of 30 Floors           5
11st   of 16 Floors          5
7th   of 8 Floors            5
4th   of 9 Floors            5
9th   of 11 Floors           5
7th   of 27 Floors           5
9th   of 30 Floors           5
8th   of 9 Floors            5
9th   of 22 Floors           5
15th   of 28 Floors          5
4th   of 27 Floors           5
6th   of 17 Floors           5
3rd   of 20 Floors           5
15th   of 18 Floors          5
18th   of 29 Floors          5
10th   of 25 Floors          5
12nd   of 29 Floors          5
5th   of 8 Floors            5
Ground of 19 Floors          5
4th   of 22 Floors           5
6th   of 20 Floors           5
15th   of 21 Floors          5
Ground of 12 Floors          5
11st   of 25 Floors          5
1st   of 12 Floors           5
10th   of 24 Floors          5
10th   of 27 Floors          5
Ground of 21 Floors          5
6th   of 11 Floors           5
16th   of 26 Floors          5
11st   of 30 Floors          5
1st   of 7 Floors            5
1st   of 15 Floors           5
14th   of 16 Floors          5
5th   of 19 Floors           5
14th   of 29 Floors          5
11st   of 29 Floors          5
12nd   of 21 Floors          5
25th   of 25 Floors          4
17th   of 25 Floors          4
13rd   of 21 Floors          4
13rd   of 19 Floors          4
20th   of 26 Floors          4
7th   of 11 Floors           4
8th   of 16 Floors           4
3rd   of 17 Floors           4
12nd   of 30 Floors          4
5th   of 16 Floors           4
7th   of 24 Floors           4
13rd   of 25 Floors          4
17th   of 26 Floors          4
15th   of 16 Floors          4
8th   of 20 Floors           4
3rd   of 10 Floors           4
2nd   of 11 Floors           4
15th   of 26 Floors          4
3rd   of 22 Floors           4
5th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 13 Floors          4
6th   of 30 Floors           4
17th   of 18 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
2nd   of 9 Floors            4
22nd   of 30 Floors          4
15th   of 23 Floors          4
Ground of 17 Floors          4
17th   of 24 Floors          4
15th   of 32 Floors          4
7th   of 9 Floors            4
3rd   of 11 Floors           4
20th   of 20 Floors          4
23rd   of 26 Floors          4
18th   of 32 Floors          4
14th   of 21 Floors          4
2nd   of 16 Floors           4
7th   of 10 Floors           4
19th   of 40 Floors          4
9th   of 10 Floors           4
12nd   of 16 Floors          4
14th   of 17 Floors          4
4th   of 8 Floors            4
11st   of 17 Floors          4
11st   of 15 Floors          4
14th   of 18 Floors          4
19th   of 24 Floors          4
1st   of 18 Floors           4
11st   of 20 Floors          4
22nd   of 24 Floors          4
3rd   of 26 Floors           3
3rd   of 16 Floors           3
10th   of 16 Floors          3
13rd   of 15 Floors          3
10th   of 28 Floors          3
12nd   of 23 Floors          3
4th   of 20 Floors           3
2nd   of 26 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
8th   of 17 Floors           3
21st   of 24 Floors          3
19th   of 21 Floors          3
17th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 21 Floors           3
27th   of 27 Floors          3
14th   of 32 Floors          3
11st   of 27 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
17th   of 20 Floors          3
4th   of 16 Floors           3
6th   of 29 Floors           3
6th   of 24 Floors           3
8th   of 25 Floors           3
30th   of 32 Floors          3
19th   of 30 Floors          3
4th   of 29 Floors           3
17th   of 29 Floors          3
18th   of 18 Floors          3
6th   of 21 Floors           3
5th   of 17 Floors           3
1st   of 25 Floors           3
5th   of 26 Floors           3
19th   of 29 Floors          3
18th   of 30 Floors          3
23rd   of 23 Floors          3
12nd   of 27 Floors          3
18th   of 26 Floors          3
8th   of 11 Floors           3
6th   of 22 Floors           3
6th   of 23 Floors           3
7th   of 23 Floors           3
15th   of 20 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
Ground of 18 Floors          3
16th   of 20 Floors          3
9th   of 21 Floors           3
3rd   of 8 Floors            3
6th   of 8 Floors            3
15th   of 39 Floors          3
20th   of 28 Floors          3
8th   of 40 Floors           3
Ground of 26 Floors          3
10th   of 30 Floors          3
26th   of 30 Floors          3
5th   of 30 Floors           3
9th   of 16 Floors           3
9th   of 40 Floors           3
11st   of 23 Floors          2
Lower Ground of 4 Floors     2
2nd   of 40 Floors           2
23rd   of 29 Floors          2
21st   of 27 Floors          2
13rd   of 20 Floors          2
9th   of 29 Floors           2
10th   of 40 Floors          2
25th   of 29 Floors          2
7th   of 22 Floors           2
13rd   of 30 Floors          2
4th   of 34 Floors           2
8th   of 23 Floors           2
9th   of 27 Floors           2
19th   of 27 Floors          2
3rd   of 24 Floors           2
27th   of 29 Floors          2
2nd   of 28 Floors           2
40th   of 40 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
2nd   of 18 Floors           2
2nd   of 7 Floors            2
2nd   of 25 Floors           2
24th   of 30 Floors          2
2nd   of 6 Floors            2
20th   of 22 Floors          2
22nd   of 25 Floors          2
2nd   of 32 Floors           2
43   of 47 Floors            2
1st   of 30 Floors           2
1st   of 20 Floors           2
15th   of 31 Floors          2
1st   of 8 Floors            2
11st   of 21 Floors          2
23rd   of 34 Floors          2
16th   of 34 Floors          2
18th   of 24 Floors          2
16th   of 30 Floors          2
16th   of 27 Floors          2
7th   of 30 Floors           2
14th   of 20 Floors          2
19th   of 20 Floors          2
16th   of 21 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 24 Floors          2
20th   of 23 Floors          2
16th   of 36 Floors          2
9th   of 28 Floors           2
2nd   of 24 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
8th   of 32 Floors           2
10th   of 32 Floors          2
Ground of 51 Floors          2
39th   of 40 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
13rd   of 40 Floors          2
20th   of 25 Floors          2
9th   of 17 Floors           2
4th   of 5 Floors            2
12nd   of 25 Floors          2
1st   of 24 Floors           2
6th   of 31 Floors           2
7th   of 29 Floors           2
1st   of 22 Floors           2
10th   of 22 Floors          2
5th   of 11 Floors           2
2nd   of 21 Floors           2
17th   of 33 Floors          2
8th   of 28 Floors           2
10th   of 11 Floors          2
Ground of 23 Floors          2
8th   of 29 Floors           2
3rd   of 27 Floors           2
14th   of 28 Floors          2
3rd   of 32 Floors           2
15th   of 17 Floors          2
16th   of 32 Floors          2
3rd   of 29 Floors           2
18th   of 21 Floors          2
15th   of 45 Floors          2
7th   of 36 Floors           2
1st   of 16 Floors           2
4th   of 11 Floors           2
5th   of 35 Floors           1
13rd   of 34 Floors          1
3rd   of 28 Floors           1
12nd   of 40 Floors          1
7th   of 40 Floors           1
13rd   of 26 Floors          1
17th   of 28 Floors          1
18th   of 35 Floors          1
22nd   of 40 Floors          1
14th   of 25 Floors          1
Ground of 2 Floors           1
16th   of 41 Floors          1
13rd   of 22 Floors          1
3rd   of 7 Floors            1
17th   of 31 Floors          1
Ground of 40 Floors          1
Ground of 5 Floors           1
21st   of 23 Floors          1
Ground of 22 Floors          1
10th   of 33 Floors          1
3rd   of 30 Floors           1
3rd   of 31 Floors           1
Lower Ground of 1 Floors     1
19th   of 32 Floors          1
Ground of 6 Floors           1
13rd   of 17 Floors          1
20th   of 24 Floors          1
45   of 47 Floors            1
22nd   of 23 Floors          1
30th   of 34 Floors          1
Ground of 25 Floors          1
16th   of 45 Floors          1
1st   of 6 Floors            1
9th   of 25 Floors           1
13rd   of 47 Floors          1
5th   of 36 Floors           1
34th   of 34 Floors          1
34th   of 42 Floors          1
9th   of 23 Floors           1
29th   of 39 Floors          1
33rd   of 33 Floors          1
27th   of 30 Floors          1
4th   of 6 Floors            1
7th   of 28 Floors           1
8th   of 35 Floors           1
Ground of 29 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
5th   of 6 Floors            1
22nd   of 26 Floors          1
3rd   of 36 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
14th   of 41 Floors          1
5th   of 34 Floors           1
24th   of 36 Floors          1
17th   of 22 Floors          1
21st   of 36 Floors          1
23rd   of 24 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
12nd   of 34 Floors          1
17th   of 47 Floors          1
18th   of 20 Floors          1
24th   of 27 Floors          1
21st   of 26 Floors          1
26th   of 47 Floors          1
7th   of 25 Floors           1
Ground of 11 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
11st   of 22 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
Ground of 24 Floors          1
35th   of 35 Floors          1
10th   of 39 Floors          1
33rd   of 48 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
29th   of 31 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
31st   of 40 Floors          1
9th   of 42 Floors           1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
16th   of 25 Floors          1
6th   of 25 Floors           1
3rd   of 40 Floors           1
12nd   of 39 Floors          1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
38th   of 40 Floors          1
15th   of 27 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [110]:
df['floorNum'].isna().sum()

2

In [111]:
df = df[~df['floorNum'].isna()]

In [112]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
842,3 BHK Flat in Sector 81 Gurgaon,dlf the ultima,2.40,11412.0,Super Built up area 2103(195.38 sq.m.),3,4,3+,servant room,"192, Sector 81 Gurgaon, Gurgaon, Haryana",19th of 30 Floors,North-West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Located in the popular residential address of ...,"['1 Fridge', '1 Fan', '1 Exhaust Fan', '1 Dini...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
364,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,1.30,10000.0,Super Built up area 1500(139.35 sq.m.)Carpet a...,3,3,2,not available,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North-East,10+ Year Old,"['Huda city centre metro station', 'Axis bank ...",Property is fully renovated with all extention...,[],"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction4 out ..."
1866,3 BHK Flat in Nirvana Country,the close north,2.50,11944.0,Super Built up area 2093(194.45 sq.m.),3,3,3,pooja room,"111, Nirvana Country, Gurgaon, Haryana",11st of 18 Floors,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","3 bhk apartment for sale in the close north, a...","['3 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Water purifier', 'Power Back-up', 'Feng Shui...","['Green Area5 out of 5', 'Construction4 out of..."
865,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.49,9030.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3,3,3,not available,"T-22/1002, Sector 102 Gurgaon, Gurgaon, Haryana",10th of 14 Floors,North-East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...","['5 Fan', '1 Exhaust Fan', '16 Light', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2367,2 BHK Flat in Sector 37D Gurgaon,signature global the millennia,0.65,10906.0,Super Built up area 650(60.39 sq.m.)Carpet are...,2,2,3,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",Ground of 16 Floors,NaN,0 to 1 Year Old,"['Jharsha Chowk', 'Hero Honda Chowk', 'Rajiv C...","Ground floor, parking facing \nAdjoining comme...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [116]:
def update_floor(x):
    x = str(x)
    if len(x) <= 2:
        print("Error 1:",x)
        return
    try:
        #print(x[:-4])
        x = int(x[:-4].strip())
    except:
        print("Error 2:",x[:-4])

    return x

In [ ]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0th  ').str.replace('Lower','0th  ').str.replace('Basement','-1th  ').apply(update_floor).astype(int)

In [117]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [119]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [120]:
df['facing'].isna().sum()

872

In [121]:
df['facing'].fillna('NA', inplace=True)

In [122]:
df['facing'].value_counts()

facing
NA            872
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [124]:
df.insert(loc=4, column='area', value=round((df['price']*10000000)/df['price_per_sqft']))

In [125]:
df.insert(loc=1,column='property_type',value='flat')

In [126]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [128]:
df.shape

(2995, 20)

In [129]:
df.to_csv('flats_cleaned.csv',index=False)